version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
      #POSTGRES_INITDB_ARGS: "-U postgres -c password_encryption=md5 -c 'create user postgres with password ''rootpass'';'"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/postgres:/var/lib/postgresql/data
      - ./config:/docker-entrypoint-initdb.d # Montar script SQL de inicialización

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: jonas@jonasmarquez.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin: