version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # Change this
      MYSQL_ROOT_HOST: "%" # Allow root access from any host
      MYSQL_DATABASE: example_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config:/docker-entrypoint-initdb.d # Montar script SQL de inicialización

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "5051:8080"

volumes:
  mysql_data: