version: '3.7'

services:
  postgres_dev:
    container_name: postgres_dev
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
      #POSTGRES_INITDB_ARGS: "-U postgres -c password_encryption=md5 -c 'create user postgres with password ''rootpass'';'"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/postgres_dev:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d # Montar script SQL de inicializaci贸n
  postgres_pre:
    container_name: postgres_pre
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
      #POSTGRES_INITDB_ARGS: "-U postgres -c password_encryption=md5 -c 'create user postgres with password ''rootpass'';'"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata/postgres_pre:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d # Montar script SQL de inicializaci贸n
  postgres_pro:
    container_name: postgres_pro
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
      #POSTGRES_INITDB_ARGS: "-U postgres -c password_encryption=md5 -c 'create user postgres with password ''rootpass'';'"
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata/postgres_pro:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d # Montar script SQL de inicializaci贸n

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: jonas@jonasmarquez.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  mysql_01:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # Change this
      MYSQL_ROOT_HOST: "%" # Allow root access from any host
      MYSQL_DATABASE: example_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d # Montar script SQL de inicializaci贸n

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "5051:8080"

volumes:
  pgdata:
  pgadmin:
  mysql_data: