version: "3.9"

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
      #volumes:
      #- ./storage/ldap_db:/var/lib/ldap
      #- ./storage/ldap_config:/etc/ldap/slapd.d
    #- ./ldap-init:/container/service/slapd/assets/config/bootstrap/ldif/custom
    environment:
      - LDAP_ORGANISATION=example
      - LDAP_DOMAIN=example.lan
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"
    hostname: openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "5052:80"
    depends_on:
      - openldap